In [92]:
import numpy as np
import pandas as pd

In [93]:
df = pd.read_excel('ETRM_extract.xlsx')
df['Due date (-)'] = df['Due date (-)'].astype('datetime64[ns]')

In [94]:
# correction of Title transfer date (-)
df['Title transfer date (-)'] = df['Title transfer date (-)'].astype(object).where(df['Title transfer date (-)'].notnull(), 0)
df['Title transfer date (-)'] = np.where(df['Title transfer date (-)'] == 0, pd.to_datetime('today') + np.timedelta64(30,'D') , df['Title transfer date (-)'])
df['Title transfer date (-)'] = df['Title transfer date (-)'].astype('datetime64[ns]')



# converting the type of Due date (-)
#df['Due date (-)'] = df['Due date (-)'].astype('datetime64[ns]')
#df['Due date (-)'] = df['Due date (-)'].dt.date

df['Due date (+)'] = df['Due date (+)'].dt.date
df['Title transfer date (-)'] = df['Title transfer date (-)'].dt.date
df['Title transfer date (+)'] = df['Title transfer date (+)'].dt.date

#correcting Due date (-)
#df['Due date (-)'] = np.where(df['Title transfer (-)'] == 1816-03-29, df['Due date (-)'], df['Due date (+)'] \
#                              - df['Title transfer (+)'] + df['Title transfer date (-)'] )

#df['Due date (-)']
#df.dtypes

In [95]:
# calculating the columns

df['Consumption Date'] = df['Due date (+)']
df['Consumption Type'] = 'Filled by Macros'
df['Total WC Consumption period'] = 10
df['TTD influence on WC consumption'] = 10
df['PDD influence on WC consumption'] = 10
df['TTD difference'] = 10
df['Sale Payment Terms'] = 10
df['Buy Payment Terms'] = 10
df['PDD difference'] = 10
df['Consumption reason'] = 'OTHER'
df['WC Amount'] = df['WC consumption amount']
df['Current price, USD/BBL (-)'] = ''


# converting columns to the right format
#converting into days
df['Total WC Consumption period'] = 10
df['TTD difference'] = 10
df['Sale Payment Terms'] = 10
df['Buy Payment Terms'] = 10
df['PDD difference'] = 10
df['TTD days'] = 10

#df.head(100)

In [96]:
def f(row):
    if (row['Total WC Consumption period'] >= row['TTD difference'] and row['Total WC Consumption period'] > 0 and row['TTD difference'] > 0) \
    or (row['Total WC Consumption period'] <= row['TTD difference'] and row['Total WC Consumption period'] < 0 and row['TTD difference'] < 0):
        return row['TTD difference']
    elif (row['Total WC Consumption period'] > 0 and row['TTD difference'] > 0) \
    or (row['Total WC Consumption period'] < 0 and row['TTD difference'] < 0):
        return row['Total WC Consumption period']
    else:
        return 0

In [97]:
df['TTD influence on WC consumption'] = df.apply(f, axis=1)
df['PDD influence on WC consumption'] = df['Total WC Consumption period'] - df['TTD influence on WC consumption']

#df.head(10)

In [98]:
# rearrange columns
cols = df.columns.tolist()
cols

['Total consumption',
 'TTL consumption',
 'Paym consumption',
 'WC consumption amount',
 'Buy/Sell (-)',
 'Buy/Sell (+)',
 'Due date (-)',
 'Due date (+)',
 'Title transfer date (-)',
 'Title transfer date (+)',
 'Strategy',
 'Strategy name',
 'Company Name',
 'Global Book name',
 'Line of Business',
 'Book Name',
 'Portfolio name',
 'Quantity',
 'Current amount in USD (+)',
 'Quantity BBL (ratio) (+)',
 'Current price, USD/BBL (+)',
 'Counterparty (+)',
 'Title transfer (+)',
 'Incoterms 1 (+)',
 'Incoterms 2 country (+)',
 'Incoterms 2 country (+).1',
 'Object type (+)',
 'Delivery ID (+)',
 'Internal type (+)',
 'Mirror Delivery ID (+)',
 'Mirror portfolio name (+)',
 'Mirror Line of Business (+)',
 'Current amount in USD (-)',
 'Quantity BBL (ratio) (-)',
 'Current price, USD/BBL (-)',
 'Counterparty (-)',
 'Title transfer (-)',
 'Incoterms 1 (-)',
 'Incoterms 2 country (-)',
 'Incoterms 2 country (-).1',
 'Object type (-)',
 'Delivery ID (-)',
 'Internal type (-)',
 'Mirror Delivery ID (-)',
 'Mirror portfolio name (-)',
 'Mirror Line of Business (-)',
 'Strategy start date',
 'Strategy end date',
 'Voyage ID (+)',
 'Transport name (+)',
 'Grade (+)',
 'Voyage ID (-)',
 'Transport name (-)',
 'Grade (-)',
 'Current amount USD (only +)',
 'Consumption Date',
 'Consumption Type',
 'Total WC Consumption period',
 'TTD influence on WC consumption',
 'PDD influence on WC consumption',
 'TTD difference',
 'Sale Payment Terms',
 'Buy Payment Terms',
 'PDD difference',
 'Consumption reason',
 'WC Amount',
 'TTD days']

In [99]:
cols = ['Consumption Date',
       'Consumption Type',
       'Total WC Consumption period',
        'TTD influence on WC consumption',
        'PDD influence on WC consumption',
        'TTD difference',
        'PDD difference',
        'Sale Payment Terms',
        'Buy Payment Terms',
        'Consumption reason',
        'WC Amount',
        'Buy/Sell (-)',
        'Buy/Sell (+)',
        'Due date (-)',
        'Due date (+)',
        'Title transfer date (-)',
        'Title transfer date (+)',
        'Strategy',
        'Strategy name',
        'Company Name',
        'Global Book name',
        'Line of Business',
        'Book Name',
        'Portfolio name',
        'Quantity',
        'Current amount in USD (+)',
        'Quantity BBL (ratio) (+)',
        'Current price, USD/BBL (+)',
        'Counterparty (+)',
        'Title transfer (+)',
        'Incoterms 1 (+)',
        'Incoterms 2 country (+)',
        'Incoterms 2 country (+).1',
        'Object type (+)',
        'Delivery ID (+)',
        'Internal type (+)',
        'Mirror Delivery ID (+)',
        'Current amount in USD (-)',
        'Quantity BBL (ratio) (-)',
        'Current price, USD/BBL (-)',
        'Counterparty (-)',
        'Title transfer (-)',
        'Incoterms 1 (-)',
        'Incoterms 2 country (-)',
        'Incoterms 2 country (-).1',
        'Object type (-)',
        'Delivery ID (-)',
        'Internal type (-)',
        'Mirror Delivery ID (-)',
        'Strategy start date',
        'Strategy end date',
        'Voyage ID (+)',
        'Transport name (+)',
        'Grade (+)',
        'Voyage ID (-)',
        'Transport name (-)',
        'Grade (-)']

In [100]:
df_sit = df[cols]
df_sit['PDD influence on WC consumption'] = 5
df_sit['Consumption Date'] = pd.to_datetime(df_sit['Consumption Date'])

/Users/daviddapaz/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/daviddapaz/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

In [101]:
df_sit.head(5)
df_sit.size

5643

In [102]:
df_sit = df_sit.reindex(np.repeat(df_sit.index.values, df_sit['TTD influence on WC consumption']), method='ffill')

In [103]:
df_sit['Consumption Date'] += pd.TimedeltaIndex(df_sit.groupby(level=0).cumcount(), unit='d')
df_export.head(20)

,Consumption Date,Consumption Type,Total WC Consumption period,TTD influence on WC consumption,PDD influence on WC consumption,TTD difference,PDD difference,Sale Payment Terms,Buy Payment Terms,Consumption reason,...,Internal type (-),Mirror Delivery ID (-),Strategy start date,Strategy end date,Voyage ID (+),Transport name (+),Grade (+),Voyage ID (-),Transport name (-),Grade (-)
0,2014-12-17,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-18,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-19,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-20,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-21,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-22,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-23,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-24,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-25,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-26,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-18,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-19,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-20,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-21,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-22,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-23,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-24,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-25,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-26,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-27,Stock in Transit,10,10,20,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA

In [104]:
df_sit['Consumption Type'] = np.where(df_sit['TTD influence on WC consumption'] > 0, 'Stock in Transit',df_sit['Consumption Type'])

In [105]:
df_sit.head(10)

,Consumption Date,Consumption Type,Total WC Consumption period,TTD influence on WC consumption,PDD influence on WC consumption,TTD difference,PDD difference,Sale Payment Terms,Buy Payment Terms,Consumption reason,...,Internal type (-),Mirror Delivery ID (-),Strategy start date,Strategy end date,Voyage ID (+),Transport name (+),Grade (+),Voyage ID (-),Transport name (-),Grade (-)
0,2014-12-17,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-18,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-19,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-20,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-21,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-22,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-23,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-24,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-25,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-26,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA

In [106]:
df_sit.size

56430

In [107]:
df_pt = df[cols]
df_pt['PDD influence on WC consumption'] = 5
df_pt['Consumption Date'] = pd.to_datetime(df_pt['Consumption Date'])
df_pt = df_pt.reindex(np.repeat(df_pt.index.values, df_pt['PDD influence on WC consumption']), method='ffill')
df_pt['Consumption Date'] += pd.TimedeltaIndex(df_pt.groupby(level=0).cumcount(), unit='d')
df_pt['Consumption Type'] = np.where(df_pt['PDD influence on WC consumption'] > 0, 'Payment Terms',df_pt['Consumption Type'])
df_pt.head(20)

/Users/daviddapaz/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/Users/daviddapaz/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()

,Consumption Date,Consumption Type,Total WC Consumption period,TTD influence on WC consumption,PDD influence on WC consumption,TTD difference,PDD difference,Sale Payment Terms,Buy Payment Terms,Consumption reason,...,Internal type (-),Mirror Delivery ID (-),Strategy start date,Strategy end date,Voyage ID (+),Transport name (+),Grade (+),Voyage ID (-),Transport name (-),Grade (-)
0,2014-12-17,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-18,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-19,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-20,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-21,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-18,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-19,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-20,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-21,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-22,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-18,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-19,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-20,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-21,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-22,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
3,2014-12-18,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
3,2014-12-19,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
3,2014-12-20,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
3,2014-12-21,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
3,2014-12-22,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA

In [112]:
df_sit.head(10)

,Consumption Date,Consumption Type,Total WC Consumption period,TTD influence on WC consumption,PDD influence on WC consumption,TTD difference,PDD difference,Sale Payment Terms,Buy Payment Terms,Consumption reason,...,Internal type (-),Mirror Delivery ID (-),Strategy start date,Strategy end date,Voyage ID (+),Transport name (+),Grade (+),Voyage ID (-),Transport name (-),Grade (-)
0,2014-12-17,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-18,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-19,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-20,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-21,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-22,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-23,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-24,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-25,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-26,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA

In [113]:
df_pt.head(10)

,Consumption Date,Consumption Type,Total WC Consumption period,TTD influence on WC consumption,PDD influence on WC consumption,TTD difference,PDD difference,Sale Payment Terms,Buy Payment Terms,Consumption reason,...,Internal type (-),Mirror Delivery ID (-),Strategy start date,Strategy end date,Voyage ID (+),Transport name (+),Grade (+),Voyage ID (-),Transport name (-),Grade (-)
0,2014-12-17,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-18,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-19,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-20,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-21,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-18,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-19,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-20,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-21,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-22,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA

In [115]:
df_new = pd.concat([df_sit, df_pt])
df_new

,Consumption Date,Consumption Type,Total WC Consumption period,TTD influence on WC consumption,PDD influence on WC consumption,TTD difference,PDD difference,Sale Payment Terms,Buy Payment Terms,Consumption reason,...,Internal type (-),Mirror Delivery ID (-),Strategy start date,Strategy end date,Voyage ID (+),Transport name (+),Grade (+),Voyage ID (-),Transport name (-),Grade (-)
0,2014-12-17,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-18,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-19,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-20,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-21,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-22,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-23,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-24,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-25,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
0,2014-12-26,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02812,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-18,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-19,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-20,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-21,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-22,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-23,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-24,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-25,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-26,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
1,2014-12-27,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04640,ROSA TOMASOS,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-18,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-19,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-20,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-21,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-22,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-23,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-24,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-25,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-26,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
2,2014-12-27,Stock in Transit,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_02305,HAFNIA KARAVA,NAPHTHA,VGN14_01042,TBA,NAPHTHA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,2015-09-15,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04752,MARILEE,NAPHTHA,NaN,NaN,NaN
93,2015-09-16,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04752,MARILEE,NAPHTHA,NaN,NaN,NaN
93,2015-09-17,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04752,MARILEE,NAPHTHA,NaN,NaN,NaN
93,2015-09-18,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04752,MARILEE,NAPHTHA,NaN,NaN,NaN
93,2015-09-19,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_04752,MARILEE,NAPHTHA,NaN,NaN,NaN
94,2018-09-10,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_00493,BALTIC FORCE,NAPHTHA,NaN,NaN,NaN
94,2018-09-11,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_00493,BALTIC FORCE,NAPHTHA,NaN,NaN,NaN
94,2018-09-12,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_00493,BALTIC FORCE,NAPHTHA,NaN,NaN,NaN
94,2018-09-13,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_00493,BALTIC FORCE,NAPHTHA,NaN,NaN,NaN
94,2018-09-14,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_00493,BALTIC FORCE,NAPHTHA,NaN,NaN,NaN
95,2014-09-24,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_00289,JS CAESAR,PROPANE,NaN,NaN,NaN
95,2014-09-25,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_00289,JS CAESAR,PROPANE,NaN,NaN,NaN
95,2014-09-26,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_00289,JS CAESAR,PROPANE,NaN,NaN,NaN
95,2014-09-27,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_00289,JS CAESAR,PROPANE,NaN,NaN,NaN
95,2014-09-28,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2000-01-01,9999-12-31 00:00:00,VGN14_00289,JS CAESAR,PROPANE,NaN,NaN,NaN
96,2014-10-14,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-21,9999-12-31 00:00:00,VGN14_01042,TBA,NAPHTHA,NaN,NaN,NaN
96,2014-10-15,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-21,9999-12-31 00:00:00,VGN14_01042,TBA,NAPHTHA,NaN,NaN,NaN
96,2014-10-16,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-21,9999-12-31 00:00:00,VGN14_01042,TBA,NAPHTHA,NaN,NaN,NaN
96,2014-10-17,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-21,9999-12-31 00:00:00,VGN14_01042,TBA,NAPHTHA,NaN,NaN,NaN
96,2014-10-18,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-21,9999-12-31 00:00:00,VGN14_01042,TBA,NAPHTHA,NaN,NaN,NaN
97,2014-09-19,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-26,9999-12-31 00:00:00,VGN14_00436,HISTRIA GIADA,NAPHTHA,NaN,NaN,NaN
97,2014-09-20,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-26,9999-12-31 00:00:00,VGN14_00436,HISTRIA GIADA,NAPHTHA,NaN,NaN,NaN
97,2014-09-21,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-26,9999-12-31 00:00:00,VGN14_00436,HISTRIA GIADA,NAPHTHA,NaN,NaN,NaN
97,2014-09-22,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-26,9999-12-31 00:00:00,VGN14_00436,HISTRIA GIADA,NAPHTHA,NaN,NaN,NaN
97,2014-09-23,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-26,9999-12-31 00:00:00,VGN14_00436,HISTRIA GIADA,NAPHTHA,NaN,NaN,NaN
98,2014-09-19,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-28,9999-12-31 00:00:00,VGN14_00413,SIGAS INGRID,PROPANE,NaN,NaN,NaN
98,2014-09-20,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-28,9999-12-31 00:00:00,VGN14_00413,SIGAS INGRID,PROPANE,NaN,NaN,NaN
98,2014-09-21,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-28,9999-12-31 00:00:00,VGN14_00413,SIGAS INGRID,PROPANE,NaN,NaN,NaN
98,2014-09-22,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-28,9999-12-31 00:00:00,VGN14_00413,SIGAS INGRID,PROPANE,NaN,NaN,NaN
98,2014-09-23,Payment Terms,10,10,5,10,10,10,10,OTHER,...,NaN,NaN,2014-08-28,9999-12-31 00:00:00,VGN14_00413,SIGAS INGRID,PROPANE,NaN,NaN,NaN

In [116]:
df_new.size

84645